typography_spectrum: 0.7095442896243185
content_rating:
  adult: false
color:
  brandStrength: 0.9375390773639083
  lightness: 0.8704230359289795
  saturation: 0.9731293888762593
  rhythmicContrast: 0.7602398064918816
  brandColors:
    - '#050503'
    - '#16430D'
    - '#29711B'
    - '#4EA44D'
    - '#74C45E'
github: true
layout_spectrum: 0.1638693881686777
author:
  name: James Harrington
  email: jamesharringtonlaw@gmail.com
  url: 'http://lacannabiz.lawyer'
name: Los Angeles Cannabis Lawyers
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: Topics you must know about to open and operate in Los Angeles
    id: 36506d3d-d316-408e-bc84-a21518e458e2
    type: content
title: 'Your Los Angeles Cannabis Business Lawyers '
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/4de35091-469b-42ba-8357-0d707ecc9ec0.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/4de35091-469b-42ba-8357-0d707ecc9ec0.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: >-
  Los Angeles cannabis business lawyers can help you navigate the legal issues
  from cultivation, transportation to commercial sale of your cannabis product. 
purpose:
  - type: email
    url: 'tel:6265896609'
    label: Call 626 589 6609 for free initial consultation
  - type: contact
    url: 'mailto:jamesharringtonlaw@gmail.com'
    label: 'Contact me:'
